package usuario;

import banco.Banco;
import dados.Vendedor;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import utilitarios.LtpUtil;
import utilitarios.LtpUtilException;

/**
 * Classe do JFrameVendedores
 * @author Natasha
 * @since 12/11/16
 * @version 1.0
 */
public class JFrameVendedores extends javax.swing.JFrame {

    /**
     * Método que cria um novo jFrame
     * @author Natasha Kaweski
     * @since 12/11/16
     * @version 1.0
     */
    public JFrameVendedores() {
        initComponents();
        this.setSize( 600, 400 );
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneVendedores = new javax.swing.JTabbedPane();
        jPanelVendedores = new javax.swing.JPanel();
        jLabelPesquisarCodigo = new javax.swing.JLabel();
        jTextFieldPesquisarCodigo = new javax.swing.JTextField();
        jButtonPesquisarCodigo = new javax.swing.JButton();
        jLabelPesquisarNome = new javax.swing.JLabel();
        jTextFieldPesquisarNome = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPanePesquisar = new javax.swing.JScrollPane();
        jTablePesquisar = new javax.swing.JTable();
        jLabelPesquisar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldIncluir = new javax.swing.JTextField();
        jButtonIncluir = new javax.swing.JButton();
        jPanelAlterarExcluir = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldBuscarPraAlterar = new javax.swing.JTextField();
        jButtonBuscarPraAlterar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelNomeAlterar = new javax.swing.JLabel();
        jTextFieldNomeAlterar = new javax.swing.JTextField();
        jButtonAlterarVendedor = new javax.swing.JButton();
        jButtonExcluirVendedor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));

        jLabelPesquisarCodigo.setText("Código");

        jButtonPesquisarCodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/imagens/search.png"))); // NOI18N
        jButtonPesquisarCodigo.setBorder(null);
        jButtonPesquisarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarCodigoActionPerformed(evt);
            }
        });

        jLabelPesquisarNome.setText("Nome");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/imagens/search.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTablePesquisar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPanePesquisar.setViewportView(jTablePesquisar);
        jTablePesquisar.getAccessibleContext().setAccessibleName("");

        jLabelPesquisar.setText("Pesquisar");

        jLabel1.setText("Incluir");

        jLabel2.setText("Nome Completo");

        jButtonIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/imagens/add.png"))); // NOI18N
        jButtonIncluir.setBorder(null);
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelVendedoresLayout = new javax.swing.GroupLayout(jPanelVendedores);
        jPanelVendedores.setLayout(jPanelVendedoresLayout);
        jPanelVendedoresLayout.setHorizontalGroup(
            jPanelVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVendedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPanePesquisar)
                    .addGroup(jPanelVendedoresLayout.createSequentialGroup()
                        .addComponent(jLabelPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(jLabelPesquisarCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldPesquisarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPesquisarCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelPesquisarNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldPesquisarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(jPanelVendedoresLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(81, 81, 81)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldIncluir)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonIncluir)))
                .addContainerGap())
        );
        jPanelVendedoresLayout.setVerticalGroup(
            jPanelVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVendedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButtonPesquisarCodigo)
                    .addGroup(jPanelVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelPesquisarCodigo)
                        .addComponent(jTextFieldPesquisarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelPesquisar))
                    .addGroup(jPanelVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelPesquisarNome)
                        .addComponent(jTextFieldPesquisarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPanePesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jTextFieldIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonIncluir))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jTabbedPaneVendedores.addTab("Pesquisar e Incluir", jPanelVendedores);

        jLabel3.setText("Código");

        jButtonBuscarPraAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/imagens/search.png"))); // NOI18N
        jButtonBuscarPraAlterar.setBorder(null);
        jButtonBuscarPraAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarPraAlterarActionPerformed(evt);
            }
        });

        jLabelNomeAlterar.setText("Nome do vendedor");

        jButtonAlterarVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/imagens/pencil.png"))); // NOI18N
        jButtonAlterarVendedor.setText("Alterar");
        jButtonAlterarVendedor.setBorder(null);
        jButtonAlterarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarVendedorActionPerformed(evt);
            }
        });

        jButtonExcluirVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/imagens/user_close.png"))); // NOI18N
        jButtonExcluirVendedor.setText("Excluir");
        jButtonExcluirVendedor.setBorder(null);
        jButtonExcluirVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirVendedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAlterarExcluirLayout = new javax.swing.GroupLayout(jPanelAlterarExcluir);
        jPanelAlterarExcluir.setLayout(jPanelAlterarExcluirLayout);
        jPanelAlterarExcluirLayout.setHorizontalGroup(
            jPanelAlterarExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlterarExcluirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAlterarExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanelAlterarExcluirLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldBuscarPraAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBuscarPraAlterar)
                        .addGap(0, 359, Short.MAX_VALUE))
                    .addGroup(jPanelAlterarExcluirLayout.createSequentialGroup()
                        .addComponent(jLabelNomeAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNomeAlterar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAlterarExcluirLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonExcluirVendedor)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAlterarVendedor)))
                .addContainerGap())
        );
        jPanelAlterarExcluirLayout.setVerticalGroup(
            jPanelAlterarExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlterarExcluirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAlterarExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldBuscarPraAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarPraAlterar))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelAlterarExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeAlterar)
                    .addComponent(jTextFieldNomeAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAlterarExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAlterarVendedor)
                    .addComponent(jButtonExcluirVendedor))
                .addContainerGap(214, Short.MAX_VALUE))
        );

        jTabbedPaneVendedores.addTab("Alterar e Excluir", jPanelAlterarExcluir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneVendedores)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneVendedores)
        );

        getAccessibleContext().setAccessibleName("Vendedores");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que pesquisa vendedor pelo código
     * @author Natasha Kaweski
     * @since 12/11/16
     * @version 1.0
     * @param evt 
     */
    private void jButtonPesquisarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarCodigoActionPerformed
        // Captura o que foi digitado no campo de texto de código
        String codigo = jTextFieldPesquisarCodigo.getText();
        
        // Validação
        if ( codigo.isEmpty() || !codigo.matches("[0-9]{1,5}") ) {
            JOptionPane.showMessageDialog(this, "O código deve conter apenas números.");
            return;
        }
        
        // Checkpoint!
        try {
            ResultSet resposta = banco.Banco.pesquisarClienteCodigo(Integer.parseInt(codigo));
            
            if ( resposta.next() ) {
                LtpUtil.loadFormatJTable(jScrollPanePesquisar, banco.Banco.pesquisarVendedorCodigo(Integer.parseInt(codigo)),false);
            } else {
                JOptionPane.showMessageDialog(this, "Não existe vendedor para o código digitado.");
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (LtpUtilException ex) {
            Logger.getLogger(JFrameCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonPesquisarCodigoActionPerformed
    
    /**
     * Método que pesquisa vendedor pelo nome
     * @author Natasha Kaweski
     * @since 12/11/16
     * @version 1.0
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Captura o que foi digitado no campo de texto de nome
        String nome = jTextFieldPesquisarNome.getText().toUpperCase();
        
        // Validação
        if ( nome.isEmpty() ) {
            JOptionPane.showMessageDialog(this, "Nome inválido.");
            return;
        }
        
        // Checkpoint!
        try {
            ResultSet resposta = banco.Banco.pesquisarVendedorNome(nome);
            
            if ( resposta.next() ) {
                LtpUtil.loadFormatJTable(jScrollPanePesquisar, banco.Banco.pesquisarVendedorNome(jTextFieldPesquisarNome.getText()),false);
            } else {
                JOptionPane.showMessageDialog(this, "Não existe vendedor para o nome digitado.");
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (LtpUtilException ex) {
            Logger.getLogger(JFrameCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * Método que cadastra um novo vendedor
     * @author Natasha Kaweski
     * @since 12/11/16
     * @version 1.0
     * @param evt 
     */
    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
       // Declaração das variáveis
        int codigo = 0;
        String nome = jTextFieldIncluir.getText().toUpperCase();
        String erro = "";
        Date dataCadVendedor = new Date(System.currentTimeMillis());
        
        // Validação dos dados do Cliente
        if ( !nome.matches("[A-Z ÇÃÕÚÁÉ]{3,40}") )
            erro = "Nome inválido.\n";
        
        // Janela contendo os erros encontrados na validação do formulário
        if ( !erro.isEmpty() ) {
            JOptionPane.showMessageDialog(this, erro + ' ' + nome);
        
        // Caso contrário, tenta inserir os dados no banco
        } else {
            Vendedor vendedor = new Vendedor(codigo, nome, dataCadVendedor);
            
            try {
                Banco.incluirVendedor(vendedor);
                JOptionPane.showMessageDialog(this, "Vendedor cadastrado com sucesso.");
                LtpUtil.loadFormatJTable(jScrollPanePesquisar, banco.Banco.listaTodosVendedores(),false);
                
                // Limpa o campo de nome
                jTextFieldIncluir.setText("");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            } catch (LtpUtilException ex) {
                Logger.getLogger(JFrameVendedores.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonIncluirActionPerformed
    
    /**
     * Método que busca um vendedor pelo código e insere seu nome no campo de nome do formulário
     * @author Natasha Kaweski
     * @since 12/11/16
     * @version 1.0
     * @param evt 
     */
    private void jButtonBuscarPraAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarPraAlterarActionPerformed
        // Captura o que foi digitado no campo de texto de código
        String codigo = jTextFieldBuscarPraAlterar.getText();
        
        // Validação
        if ( codigo.isEmpty() || !codigo.matches("[0-9]{1,5}") ) {
            JOptionPane.showMessageDialog(this, "O código deve conter apenas números.");
            return;
        }
        
        // Checkpoint!
        try {
            ResultSet resposta = banco.Banco.pesquisarVendedorCodigo(Integer.parseInt(codigo));
            
            if ( resposta.next() ) jTextFieldNomeAlterar.setText( resposta.getNString("NOME_VENDEDOR") );
            else JOptionPane.showMessageDialog(this, "Não existe vendedor para o código digitado.");
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButtonBuscarPraAlterarActionPerformed

    /**
     * Método que altera um vendedor já cadastrado
     * @author Natasha Kaweski
     * @since 12/11/16
     * @version 1.0
     * @param evt 
     */
    private void jButtonAlterarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarVendedorActionPerformed
        // Captura o que foi digitado no campo de texto de código
        String codigo = jTextFieldBuscarPraAlterar.getText();
        
        // Validação do campo do código
        if ( codigo.isEmpty() || !codigo.matches("[0-9]{1,5}") ) {
            JOptionPane.showMessageDialog(this, "O código deve conter apenas números.");
            return;
        } 
        
        // Checkpoint!
        try {
            ResultSet resposta = banco.Banco.pesquisarVendedorCodigo(Integer.parseInt(codigo));
            
            if ( resposta.next() ) {
        
                // Declaração das variáveis
                String nome = jTextFieldNomeAlterar.getText().toUpperCase();
                String erro = "";
                Date data = new Date(System.currentTimeMillis());

                // Validação dos dados do Vendedor
                if ( !nome.matches("[A-Z ÇÃÕÚÁÉ]{3,40}") )
                    erro = "Nome inválido.\n";

                // Janela contendo os erros encontrados na validação do formulário
                if ( !erro.isEmpty() ) {
                    JOptionPane.showMessageDialog(this, erro + ' ' + nome);

                // Caso contrário, tenta inserir os dados no banco
                } else {
                    Vendedor vendedor = new Vendedor(Integer.parseInt(codigo), nome, data);

                    try {
                        Banco.alterarVendedor(vendedor);
                        JOptionPane.showMessageDialog(this, "Vendedor alterado com sucesso.");
                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(this, e.getMessage());
                    }
                }
                
            } else {
                JOptionPane.showMessageDialog(this, "Não existe cliente para o código digitado.");
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButtonAlterarVendedorActionPerformed
    
    /**
     * Método que exclui um vendedor do banco
     * @author Natasha Kaweski
     * @since 12/11/16
     * @version 1.0
     * @param evt 
     */
    private void jButtonExcluirVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirVendedorActionPerformed
        // Pega o cliente com o código informado
        String codigo = jTextFieldBuscarPraAlterar.getText();
        
        // Validação
        if ( codigo.isEmpty() || !codigo.matches("[0-9]{1,5}") ) {
            JOptionPane.showMessageDialog(this, "O código deve conter apenas números.");
            return;
        }
        
        int reply = JOptionPane.showConfirmDialog(null, "Confirmar exclusão?", "Deletar vendedor", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            try {
                banco.Banco.excluirVendedor(Integer.parseInt(codigo));
                JOptionPane.showMessageDialog(this, "Vendedor excluído.");
                
                jTextFieldBuscarPraAlterar.setText("");
                jTextFieldNomeAlterar.setText("");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonExcluirVendedorActionPerformed

    /**
     * Método Main
     * @param args 
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameVendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameVendedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAlterarVendedor;
    private javax.swing.JButton jButtonBuscarPraAlterar;
    private javax.swing.JButton jButtonExcluirVendedor;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButtonPesquisarCodigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelNomeAlterar;
    private javax.swing.JLabel jLabelPesquisar;
    private javax.swing.JLabel jLabelPesquisarCodigo;
    private javax.swing.JLabel jLabelPesquisarNome;
    private javax.swing.JPanel jPanelAlterarExcluir;
    private javax.swing.JPanel jPanelVendedores;
    private javax.swing.JScrollPane jScrollPanePesquisar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPaneVendedores;
    private javax.swing.JTable jTablePesquisar;
    private javax.swing.JTextField jTextFieldBuscarPraAlterar;
    private javax.swing.JTextField jTextFieldIncluir;
    private javax.swing.JTextField jTextFieldNomeAlterar;
    private javax.swing.JTextField jTextFieldPesquisarCodigo;
    private javax.swing.JTextField jTextFieldPesquisarNome;
    // End of variables declaration//GEN-END:variables
}
