package usuario;

import java.util.GregorianCalendar;
import java.util.HashMap;
import javax.swing.JOptionPane;
import utilitarios.LtpUtil;

/**
 * Classe JFrameiReportProdutos
 * @author Natasha Kaweski
 * @since 12/11/16
 * @version 1.0
 */
public class JFrameiReportProdutos extends javax.swing.JFrame {

    /**
     * Método que cria um novo jFrame
     * @author Natasha Kaweski
     * @since 12/11/16
     * @version 1.0
     */
    public JFrameiReportProdutos() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneRelatorioData = new javax.swing.JTabbedPane();
        jPanelRelatorioData = new javax.swing.JPanel();
        jDateChooserInicio = new com.toedter.calendar.JDateChooser();
        jDateChooserFinal = new com.toedter.calendar.JDateChooser();
        jLabelRelatorioDataInicio = new javax.swing.JLabel();
        jLabelRelatorioDataFinal = new javax.swing.JLabel();
        jButtonGerarRelatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPaneRelatorioData.setPreferredSize(new java.awt.Dimension(353, 339));

        jLabelRelatorioDataInicio.setText("Início");

        jLabelRelatorioDataFinal.setText("Final");

        jButtonGerarRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/imagens/activity_monitor_chart.png"))); // NOI18N
        jButtonGerarRelatorio.setText("Gerar Relatório");
        jButtonGerarRelatorio.setBorder(null);
        jButtonGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerarRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRelatorioDataLayout = new javax.swing.GroupLayout(jPanelRelatorioData);
        jPanelRelatorioData.setLayout(jPanelRelatorioDataLayout);
        jPanelRelatorioDataLayout.setHorizontalGroup(
            jPanelRelatorioDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRelatorioDataLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanelRelatorioDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonGerarRelatorio)
                    .addGroup(jPanelRelatorioDataLayout.createSequentialGroup()
                        .addGroup(jPanelRelatorioDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRelatorioDataInicio)
                            .addComponent(jLabelRelatorioDataFinal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelRelatorioDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooserInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooserFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanelRelatorioDataLayout.setVerticalGroup(
            jPanelRelatorioDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRelatorioDataLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanelRelatorioDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRelatorioDataInicio)
                    .addComponent(jDateChooserInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanelRelatorioDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRelatorioDataFinal)
                    .addComponent(jDateChooserFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jButtonGerarRelatorio)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jTabbedPaneRelatorioData.addTab("Data do Relatório de Produtos", jPanelRelatorioData);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneRelatorioData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneRelatorioData, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que gera relatório ao validar as datas selecionadas
     * @param evt 
     * @author Natasha Kaweski
     * @since 11/11/16
     * @version 1.2
     */
    private void jButtonGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerarRelatorioActionPerformed
        GregorianCalendar menorData = new GregorianCalendar();
        GregorianCalendar maiorData = new GregorianCalendar();
        
//        // Validando datas
//        if (!LtpUtil.validarData(jDateChooserInicio.getDateFormatString(), menorData)) {
//            JOptionPane.showMessageDialog(this, "Data inicial inválida.", "Relação de Produtos", JOptionPane.WARNING_MESSAGE);
//            jDateChooserInicio.requestFocus();
//            return;
//        }
//        
//        if (!LtpUtil.validarData(jDateChooserFinal.getDateFormatString(), maiorData)) {
//            JOptionPane.showMessageDialog(this, "Data final inválida.", "Relação de Produtos", JOptionPane.WARNING_MESSAGE);
//            jDateChooserFinal.requestFocus();
//            return;
//        }
//        
//        if (menorData.compareTo(maiorData)>0) {
//            JOptionPane.showMessageDialog(this, "Data final menor que a data inicial.", "Relação de Produtos", JOptionPane.WARNING_MESSAGE);
//            jDateChooserInicio.requestFocus();
//            return;
//        }
        
        HashMap<String,Object> parametros = new HashMap<String, Object>();
        parametros.put("dataIni", menorData.getTime());
        parametros.put("dataFim", maiorData.getTime());
        
        // Gera relatório
        try {
            LtpUtil.gerarRelatorio(LtpUtil.RELATORIO_VISUALIZADOR_JASPER, banco.Banco.con, parametros, 
                    getClass().getResource("relatorios/relatorioProduto.jasper").openStream(), "Relatório de Produtos");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButtonGerarRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameiReportProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameiReportProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameiReportProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameiReportProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameiReportProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGerarRelatorio;
    private com.toedter.calendar.JDateChooser jDateChooserFinal;
    private com.toedter.calendar.JDateChooser jDateChooserInicio;
    private javax.swing.JLabel jLabelRelatorioDataFinal;
    private javax.swing.JLabel jLabelRelatorioDataInicio;
    private javax.swing.JPanel jPanelRelatorioData;
    private javax.swing.JTabbedPane jTabbedPaneRelatorioData;
    // End of variables declaration//GEN-END:variables
}
