package usuario;

import banco.Banco;
import dados.Cliente;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import utilitarios.LtpUtil;
import utilitarios.LtpUtilException;

/**
 * Classe do JFrameCliente
 * @author Natasha
 * @since 30/10/16
 * @version 2.0
 */
public class JFrameCliente extends javax.swing.JFrame {
    
    /**
     * Método que cria um novo jFrame
     * @author Natasha Kaweski
     * @since 30/10/16
     * @version 2.0
     */
    public JFrameCliente() {
        initComponents();
        this.setSize( 600, 400 );
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPanePesquisarCodigo = new javax.swing.JTabbedPane();
        jPanelPesquisarCliente = new javax.swing.JPanel();
        jLabelPesquisarCodigo = new javax.swing.JLabel();
        jTextFieldPesquisarCodigo = new javax.swing.JTextField();
        jButtonPesquisarCodigo = new javax.swing.JButton();
        jLabelPesquisarNome = new javax.swing.JLabel();
        jTextFieldPesquisarNome = new javax.swing.JTextField();
        jButtonPesquisarNome = new javax.swing.JButton();
        jScrollPanePesquisa = new javax.swing.JScrollPane();
        jTablePesquisa = new javax.swing.JTable();
        jPanelIncluirCliente = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelEndereco = new javax.swing.JLabel();
        jTextFieldEndereco = new javax.swing.JTextField();
        jLabelBairro = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabelCidade = new javax.swing.JLabel();
        jTextFieldCidade = new javax.swing.JTextField();
        jLabelEstado = new javax.swing.JLabel();
        jTextFieldEstado = new javax.swing.JTextField();
        jLabelHelpEstado = new javax.swing.JLabel();
        jLabelCEP = new javax.swing.JLabel();
        jTextFieldCEP = new javax.swing.JTextField();
        jLabelHelpCEP = new javax.swing.JLabel();
        jLabelTelefone = new javax.swing.JLabel();
        jLabelHelpTelefone = new javax.swing.JLabel();
        jTextFieldTelefone = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelHelpEmail = new javax.swing.JLabel();
        jButtonCadastrar = new javax.swing.JButton();
        jPanelIncluir = new javax.swing.JPanel();
        jLabelCodigo = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jButtonCodigo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelAlterarNome = new javax.swing.JLabel();
        jTextFieldAlterarNome = new javax.swing.JTextField();
        jLabelAlterarEndereco = new javax.swing.JLabel();
        jTextFieldAlterarEndereco = new javax.swing.JTextField();
        jLabelAlterarBairro = new javax.swing.JLabel();
        jTextFieldAlterarBairro = new javax.swing.JTextField();
        jLabelAlterarCidade = new javax.swing.JLabel();
        jTextFieldAlterarCidade = new javax.swing.JTextField();
        jLabelAlterarEstado = new javax.swing.JLabel();
        jLabelAlterarCEP = new javax.swing.JLabel();
        jTextFieldAlterarEstado = new javax.swing.JTextField();
        jTextFieldAlterarCEP = new javax.swing.JTextField();
        jLabelAlterarTelefone = new javax.swing.JLabel();
        jTextFieldAlterarTelefone = new javax.swing.JTextField();
        jLabelAlterarEmail = new javax.swing.JLabel();
        jTextFieldAlterarEmail = new javax.swing.JTextField();
        jButtonAlterar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clientes");

        jPanelPesquisarCliente.setMaximumSize(new java.awt.Dimension(600, 400));
        jPanelPesquisarCliente.setPreferredSize(new java.awt.Dimension(600, 400));

        jLabelPesquisarCodigo.setText("Código");

        jButtonPesquisarCodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/imagens/search.png"))); // NOI18N
        jButtonPesquisarCodigo.setBorder(null);
        jButtonPesquisarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarCodigoActionPerformed(evt);
            }
        });

        jLabelPesquisarNome.setText("Nome");

        jButtonPesquisarNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/imagens/search.png"))); // NOI18N
        jButtonPesquisarNome.setBorder(null);
        jButtonPesquisarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarNomeActionPerformed(evt);
            }
        });

        jScrollPanePesquisa.setBorder(null);
        jScrollPanePesquisa.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTablePesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTablePesquisa.setCellSelectionEnabled(true);
        jTablePesquisa.setRowHeight(20);
        jTablePesquisa.setRowMargin(2);
        jTablePesquisa.setShowGrid(false);
        jScrollPanePesquisa.setViewportView(jTablePesquisa);

        javax.swing.GroupLayout jPanelPesquisarClienteLayout = new javax.swing.GroupLayout(jPanelPesquisarCliente);
        jPanelPesquisarCliente.setLayout(jPanelPesquisarClienteLayout);
        jPanelPesquisarClienteLayout.setHorizontalGroup(
            jPanelPesquisarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesquisarClienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelPesquisarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelPesquisarClienteLayout.createSequentialGroup()
                        .addComponent(jLabelPesquisarCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldPesquisarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPesquisarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelPesquisarNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPesquisarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jButtonPesquisarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPanePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPesquisarClienteLayout.setVerticalGroup(
            jPanelPesquisarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesquisarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPesquisarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelPesquisarNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPesquisarCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPesquisarCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jTextFieldPesquisarNome, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPesquisarCodigo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonPesquisarNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPanePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTabbedPanePesquisarCodigo.addTab("Pesquisar", jPanelPesquisarCliente);

        jLabelNome.setText("Nome completo");

        jLabelEndereco.setText("Endereço");

        jLabelBairro.setText("Bairro");

        jLabelCidade.setText("Cidade");

        jLabelEstado.setText("Estado");

        jLabelHelpEstado.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabelHelpEstado.setText("Exemplo: MG");

        jLabelCEP.setText("CEP");

        jLabelHelpCEP.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabelHelpCEP.setText("Exemplo: 11222333");

        jLabelTelefone.setText("Telefone");

        jLabelHelpTelefone.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabelHelpTelefone.setText("Exemplo: (00) 00000-0000");

        jLabelEmail.setText("E-mail");

        jLabelHelpEmail.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabelHelpEmail.setText("Exemplo: joe@doe.com");

        jButtonCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/imagens/add.png"))); // NOI18N
        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.setBorder(null);
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelIncluirClienteLayout = new javax.swing.GroupLayout(jPanelIncluirCliente);
        jPanelIncluirCliente.setLayout(jPanelIncluirClienteLayout);
        jPanelIncluirClienteLayout.setHorizontalGroup(
            jPanelIncluirClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelIncluirClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelIncluirClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelIncluirClienteLayout.createSequentialGroup()
                        .addGroup(jPanelIncluirClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEndereco)
                            .addComponent(jLabelBairro)
                            .addComponent(jLabelEstado)
                            .addComponent(jLabelTelefone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelIncluirClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelHelpTelefone)
                            .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHelpEstado)
                            .addComponent(jTextFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelIncluirClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCidade)
                            .addComponent(jLabelCEP)
                            .addComponent(jLabelEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelIncluirClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCEP)
                            .addComponent(jTextFieldEmail)
                            .addGroup(jPanelIncluirClienteLayout.createSequentialGroup()
                                .addGroup(jPanelIncluirClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelHelpEmail)
                                    .addComponent(jLabelHelpCEP))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextFieldCidade)))
                    .addGroup(jPanelIncluirClienteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanelIncluirClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonCadastrar)
                            .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelIncluirClienteLayout.createSequentialGroup()
                                .addComponent(jLabelNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(29, 29, 29))
        );
        jPanelIncluirClienteLayout.setVerticalGroup(
            jPanelIncluirClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIncluirClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelIncluirClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanelIncluirClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelIncluirClienteLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelIncluirClienteLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabelEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(jPanelIncluirClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabelCidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldCidade)
                    .addComponent(jLabelBairro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addGroup(jPanelIncluirClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelCEP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelEstado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldEstado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jTextFieldCEP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIncluirClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHelpEstado, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelHelpCEP, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelIncluirClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabelEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldEmail)
                    .addComponent(jLabelTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIncluirClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHelpTelefone, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelHelpEmail, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCadastrar)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jTextFieldNome.getAccessibleContext().setAccessibleName("Nome");
        jTextFieldNome.getAccessibleContext().setAccessibleDescription("Nome");

        jTabbedPanePesquisarCodigo.addTab("Incluir", jPanelIncluirCliente);

        jLabelCodigo.setText("Código");

        jButtonCodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/imagens/search.png"))); // NOI18N
        jButtonCodigo.setText("Pesquisar");
        jButtonCodigo.setBorder(null);
        jButtonCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCodigoActionPerformed(evt);
            }
        });

        jLabelAlterarNome.setText("Nome");

        jLabelAlterarEndereco.setText("Endereço");

        jLabelAlterarBairro.setText("Bairro");

        jLabelAlterarCidade.setText("Cidade");

        jLabelAlterarEstado.setText("Estado");

        jLabelAlterarCEP.setText("CEP");

        jLabelAlterarTelefone.setText("Telefone");

        jLabelAlterarEmail.setText("E-mail");

        jButtonAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/imagens/pencil.png"))); // NOI18N
        jButtonAlterar.setText("Alterar");
        jButtonAlterar.setBorder(null);
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/imagens/page_blank_close.png"))); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setBorder(null);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelIncluirLayout = new javax.swing.GroupLayout(jPanelIncluir);
        jPanelIncluir.setLayout(jPanelIncluirLayout);
        jPanelIncluirLayout.setHorizontalGroup(
            jPanelIncluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIncluirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelIncluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanelIncluirLayout.createSequentialGroup()
                        .addGroup(jPanelIncluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAlterarEstado)
                            .addComponent(jLabelAlterarBairro))
                        .addGroup(jPanelIncluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelIncluirLayout.createSequentialGroup()
                                .addGap(256, 256, 256)
                                .addComponent(jLabelAlterarCidade))
                            .addGroup(jPanelIncluirLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jTextFieldAlterarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelAlterarCEP)))
                        .addGap(17, 17, 17)
                        .addGroup(jPanelIncluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldAlterarCEP)
                            .addComponent(jTextFieldAlterarCidade)))
                    .addGroup(jPanelIncluirLayout.createSequentialGroup()
                        .addComponent(jLabelAlterarTelefone)
                        .addGap(20, 20, 20)
                        .addComponent(jTextFieldAlterarTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelAlterarEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldAlterarEmail))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelIncluirLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAlterar))
                    .addGroup(jPanelIncluirLayout.createSequentialGroup()
                        .addGroup(jPanelIncluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAlterarEndereco)
                            .addComponent(jLabelAlterarNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelIncluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldAlterarNome)
                            .addGroup(jPanelIncluirLayout.createSequentialGroup()
                                .addComponent(jTextFieldAlterarBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextFieldAlterarEndereco, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanelIncluirLayout.createSequentialGroup()
                        .addComponent(jLabelCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCodigo)
                        .addGap(0, 206, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelIncluirLayout.setVerticalGroup(
            jPanelIncluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIncluirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelIncluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIncluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAlterarNome)
                    .addComponent(jTextFieldAlterarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelIncluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAlterarEndereco)
                    .addComponent(jTextFieldAlterarEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelIncluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAlterarBairro)
                    .addComponent(jTextFieldAlterarBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAlterarCidade)
                    .addComponent(jTextFieldAlterarCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelIncluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAlterarEstado)
                    .addComponent(jLabelAlterarCEP)
                    .addComponent(jTextFieldAlterarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAlterarCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelIncluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAlterarTelefone)
                    .addComponent(jTextFieldAlterarTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAlterarEmail)
                    .addComponent(jTextFieldAlterarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelIncluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAlterar)
                    .addComponent(jButtonExcluir))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jTabbedPanePesquisarCodigo.addTab("Alterar", jPanelIncluir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPanePesquisarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPanePesquisarCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que pesquisa cliente pelo código
     * @author Natasha Kaweski
     * @since 10/11/16
     * @version 1.1
     * @param evt 
     */
    private void jButtonPesquisarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarCodigoActionPerformed
        // Captura o que foi digitado no campo de texto de código
        String codigo = jTextFieldPesquisarCodigo.getText();
        
        // Validação
        if ( codigo.isEmpty() || !codigo.matches("[0-9]{1,5}") ) {
            JOptionPane.showMessageDialog(this, "O código deve conter apenas números.");
            return;
        }
        
        // Checkpoint!
        try {
            ResultSet resposta = banco.Banco.pesquisarClienteCodigo(Integer.parseInt(codigo));
            
            if ( resposta.next() ) {
                LtpUtil.loadFormatJTable(jScrollPanePesquisa, banco.Banco.pesquisarClienteCodigo(Integer.parseInt(codigo)),false);
            } else {
                JOptionPane.showMessageDialog(this, "Não existe cliente para o código digitado.");
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (LtpUtilException ex) {
            Logger.getLogger(JFrameCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonPesquisarCodigoActionPerformed
    
    /**
     * Método que pesquis cliente pelo nome
     * @author Natasha Kaweski
     * @since 10/11/16
     * @version 1.2
     * @param evt 
     */
    private void jButtonPesquisarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarNomeActionPerformed
        // Captura o que foi digitado no campo de texto de nome
        String nome = jTextFieldPesquisarNome.getText().toUpperCase();
        
        // Validação
        if ( nome.isEmpty() ) {
            JOptionPane.showMessageDialog(this, "Nome inválido.");
            return;
        }
        
        // Checkpoint!
        try {
            ResultSet resposta = banco.Banco.pesquisarClienteNome(nome);
            
            if ( resposta.next() ) {
                LtpUtil.loadFormatJTable(jScrollPanePesquisa, banco.Banco.pesquisarClienteNome(jTextFieldPesquisarNome.getText()),false);
            } else {
                JOptionPane.showMessageDialog(this, "Não existe cliente para o nome digitado.");
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (LtpUtilException ex) {
            Logger.getLogger(JFrameCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonPesquisarNomeActionPerformed
    
    /**
     * Método que cadastra um novo cliente
     * @author Natasha Kaweski
     * @since 6/11/16
     * @version 2.1
     * @param evt 
     */
    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        // Declaração das variáveis
        int codigo = 0;
        String nome = jTextFieldNome.getText().toUpperCase();
        String endereco = jTextFieldEndereco.getText().toUpperCase();
        String bairro = jTextFieldBairro.getText().toUpperCase();
        String cidade = jTextFieldCidade.getText().toUpperCase();
        String estado = jTextFieldEstado.getText().toUpperCase();
        String cep = jTextFieldCEP.getText();
        String telefone = jTextFieldTelefone.getText();
        String email = jTextFieldEmail.getText().toUpperCase();
        String erro = "";
        Date data = new Date(System.currentTimeMillis());
        
        // Validação dos dados do Cliente
        if ( !nome.matches("[A-Z ÇÃÕÚÁÉ]{3,40}") )
            erro = "Nome inválido.\n";
        
        if ( endereco.isEmpty() )
            erro += "Endereço inválido.\n";
        
        if ( bairro.isEmpty() )
            erro += "Bairro inválido.\n";
        
        if ( cidade.isEmpty() )
            erro += "Cidade inválida.\n";
        
        if ( !estado.matches("\\w{2}$") )
            erro += "Estado inválido.\n";
        
        if ( !cep.matches("[0-9]{5}[0-9]{3}$") )
            erro += "CEP inválido.\n";
        
        if ( !telefone.matches("^\\([1-9]{2}\\) [2-9][0-9]{3,4}\\-[0-9]{4}$") )
            erro += "Telefone inválido.\n";
        
        if ( !email.matches("\\w+@\\w+[.]\\w{3}[.]\\w{2}|\\w+@\\w+[.]\\w{2,3}") )
            erro += "E-mail inválido.";
        
        // Janela contendo os erros encontrados na validação do formulário
        if ( !erro.isEmpty() ) {
            JOptionPane.showMessageDialog(this, erro + ' ' + nome);
        
        // Caso contrário, tenta inserir os dados no banco
        } else {
            Cliente cliente = new Cliente(codigo, nome, endereco, bairro, cidade, estado, cep, telefone, email, data);
            
            try {
                Banco.incluirCliente(cliente);
                JOptionPane.showMessageDialog(this, "Cliente cadastrado com sucesso.");
                
                // Limpa os campos de inclusão
                jTextFieldNome.setText("");
                jTextFieldEndereco.setText("");
                jTextFieldBairro.setText("");
                jTextFieldCidade.setText("");
                jTextFieldEstado.setText("");
                jTextFieldCEP.setText("");
                jTextFieldTelefone.setText("");
                jTextFieldEmail.setText("");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    /**
     * Método que altera um cliente já cadastrado
     * @author Natasha Kaweski
     * @since 10/11/16
     * @version 1.3
     * @param evt 
     */
    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        // Captura o que foi digitado no campo de texto de código
        String codigo = jTextFieldCodigo.getText();
        
        // Validação do campo do código
        if ( codigo.isEmpty() || !codigo.matches("[0-9]{1,5}") ) {
            JOptionPane.showMessageDialog(this, "O código deve conter apenas números.");
            return;
        } 
        
        // Checkpoint!
        try {
            ResultSet resposta = banco.Banco.pesquisarClienteCodigo(Integer.parseInt(codigo));
            
            if ( resposta.next() ) {
        
                // Declaração das variáveis
                String nome = jTextFieldAlterarNome.getText().toUpperCase();
                String endereco = jTextFieldAlterarEndereco.getText().toUpperCase();
                String bairro = jTextFieldAlterarBairro.getText().toUpperCase();
                String cidade = jTextFieldAlterarCidade.getText().toUpperCase();
                String estado = jTextFieldAlterarEstado.getText().toUpperCase();
                String cep = jTextFieldAlterarCEP.getText();
                String telefone = jTextFieldAlterarTelefone.getText();
                String email = jTextFieldAlterarEmail.getText().toUpperCase();
                String erro = "";
                Date data = new Date(System.currentTimeMillis());

                // Validação dos dados do Cliente
                if ( !nome.matches("[A-Z ÇÃÕÚÁÉ]{3,40}") )
                    erro = "Nome inválido.\n";

                if ( endereco.isEmpty() )
                    erro += "Endereço inválido.\n";

                if ( bairro.isEmpty() )
                    erro += "Bairro inválido.\n";

                if ( cidade.isEmpty() )
                    erro += "Cidade inválida.\n";

                if ( !estado.matches("\\w{2}$") )
                    erro += "Estado inválido.\n";

                if ( !cep.matches("[0-9]{5}[0-9]{3}$") )
                    erro += "CEP inválido.\n";

                if ( !telefone.matches("^\\([1-9]{2}\\) [2-9][0-9]{3,4}\\-[0-9]{4}$") )
                    erro += "Telefone inválido.\n";

                if ( !email.matches("\\w+@\\w+[.]\\w{3}[.]\\w{2}|\\w+@\\w+[.]\\w{2,3}") )
                    erro += "E-mail inválido.";

                // Janela contendo os erros encontrados na validação do formulário
                if ( !erro.isEmpty() ) {
                    JOptionPane.showMessageDialog(this, erro + ' ' + nome);

                // Caso contrário, tenta inserir os dados no banco
                } else {
//                    Cliente cliente = new Cliente(codigo, nome, endereco, bairro, cidade, estado, cep, data);
                    Cliente cliente = new Cliente(Integer.parseInt(codigo), nome, endereco, bairro, cidade, estado, cep, telefone, email, data);

                    try {
                        Banco.alterarCliente(cliente);
                        JOptionPane.showMessageDialog(this, "Cliente alterado com sucesso.");
                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(this, e.getMessage());
                    }
                }
                
            } else {
                JOptionPane.showMessageDialog(this, "Não existe cliente para o código digitado.");
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    /**
     * Método que busca um cliente pelo código e insere seus dados nos campos do formulário
     * @author Natasha Kaweski
     * @since 10/11/16
     * @version 1.0
     * @param evt 
     */
    private void jButtonCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCodigoActionPerformed
        // Captura o que foi digitado no campo de texto de código
        String codigo = jTextFieldCodigo.getText();
        
        // Validação
        if ( codigo.isEmpty() || !codigo.matches("[0-9]{1,5}") ) {
            JOptionPane.showMessageDialog(this, "O código deve conter apenas números.");
            return;
        }
        
        // Checkpoint!
        try {
            ResultSet resposta = banco.Banco.pesquisarClienteCodigo(Integer.parseInt(codigo));
            
            if ( resposta.next() ) {
                jTextFieldAlterarNome.setText( resposta.getNString("NOME") );
                jTextFieldAlterarEndereco.setText( resposta.getNString("ENDERECO") );
                jTextFieldAlterarBairro.setText( resposta.getNString("BAIRRO") );
                jTextFieldAlterarCidade.setText( resposta.getNString("CIDADE") );
                jTextFieldAlterarEstado.setText( resposta.getNString("UF") );
                jTextFieldAlterarCEP.setText( resposta.getNString("CEP") );
                jTextFieldAlterarTelefone.setText( resposta.getNString("TELEFONE") );
                jTextFieldAlterarEmail.setText( resposta.getNString("E_MAIL") );
                
            } else {
                JOptionPane.showMessageDialog(this, "Não existe cliente para o código digitado.");
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButtonCodigoActionPerformed

    /**
     * Método que exclui um cliente do banco
     * @author Natasha Kaweski
     * @since 10/11/16
     * @version 1.1
     * @param evt 
     */
    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // Pega o cliente com o código informado
        String codigo = jTextFieldCodigo.getText();
        
        // Validação
        if ( codigo.isEmpty() || !codigo.matches("[0-9]{1,5}") ) {
            JOptionPane.showMessageDialog(this, "O código deve conter apenas números.");
            return;
        }
        
        int reply = JOptionPane.showConfirmDialog(null, "Confirmar exclusão?", "Deletar cliente", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            try {
                banco.Banco.excluirCliente(Integer.parseInt(codigo));
                JOptionPane.showMessageDialog(this, "Cliente excluído.");
                
                jTextFieldCodigo.setText("");
                jTextFieldAlterarNome.setText("");
                jTextFieldAlterarEndereco.setText("");
                jTextFieldAlterarBairro.setText("");
                jTextFieldAlterarEstado.setText("");
                jTextFieldAlterarCidade.setText("");
                jTextFieldAlterarTelefone.setText("");
                jTextFieldAlterarEmail.setText("");
                jTextFieldAlterarCEP.setText("");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
        
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    /**
     * Método Main
     * @param args 
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonCodigo;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonPesquisarCodigo;
    private javax.swing.JButton jButtonPesquisarNome;
    private javax.swing.JLabel jLabelAlterarBairro;
    private javax.swing.JLabel jLabelAlterarCEP;
    private javax.swing.JLabel jLabelAlterarCidade;
    private javax.swing.JLabel jLabelAlterarEmail;
    private javax.swing.JLabel jLabelAlterarEndereco;
    private javax.swing.JLabel jLabelAlterarEstado;
    private javax.swing.JLabel jLabelAlterarNome;
    private javax.swing.JLabel jLabelAlterarTelefone;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelCEP;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelHelpCEP;
    private javax.swing.JLabel jLabelHelpEmail;
    private javax.swing.JLabel jLabelHelpEstado;
    private javax.swing.JLabel jLabelHelpTelefone;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPesquisarCodigo;
    private javax.swing.JLabel jLabelPesquisarNome;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JPanel jPanelIncluir;
    private javax.swing.JPanel jPanelIncluirCliente;
    private javax.swing.JPanel jPanelPesquisarCliente;
    private javax.swing.JScrollPane jScrollPanePesquisa;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPanePesquisarCodigo;
    private javax.swing.JTable jTablePesquisa;
    private javax.swing.JTextField jTextFieldAlterarBairro;
    private javax.swing.JTextField jTextFieldAlterarCEP;
    private javax.swing.JTextField jTextFieldAlterarCidade;
    private javax.swing.JTextField jTextFieldAlterarEmail;
    private javax.swing.JTextField jTextFieldAlterarEndereco;
    private javax.swing.JTextField jTextFieldAlterarEstado;
    private javax.swing.JTextField jTextFieldAlterarNome;
    private javax.swing.JTextField jTextFieldAlterarTelefone;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCEP;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldEstado;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPesquisarCodigo;
    private javax.swing.JTextField jTextFieldPesquisarNome;
    private javax.swing.JTextField jTextFieldTelefone;
    // End of variables declaration//GEN-END:variables
}
